language: go

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get -t ./...

script:
- go test -v -covermode=count -coverprofile=coverage.out ./...
- $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out
